# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import pathlib
parent_path = pathlib.Path(__file__).resolve().parent.parent

# Only the project root is needed; qpandalite/ lives directly under it.
sys.path.insert(0, os.path.abspath(parent_path))

# Read version from pyproject.toml or use fallback
try:
    import tomllib
    with open(parent_path / 'pyproject.toml', 'rb') as _f:
        _toml = tomllib.load(_f)
    release = _toml['project']['version']
except Exception:
    try:
        exec(open(parent_path / 'qpandalite' / 'version.py').read())
        release = __version__
    except Exception:
        release = '0.1.0'

copyright = '2025, Agony5757'
author = ', '.join(['Agony5757', 'YunJ1e', 'automatic-code-ztr', 'didaozi'])
project = 'QPanda-lite'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    # 'recommonmark',
    'myst_parser',
    'sphinx.ext.viewcode'
]

# -- Options for myst_parser
# See https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "attrs_block",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# Suppress myst xref_missing warnings (cross-doc anchor references in markdown)
myst_ref_domains = None
suppress_warnings = ["myst.xref_missing"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# Sphinx's autodoc can be configured to mock certain imports so that they don't actually get executed. 
autodoc_mock_imports = ["qiskit", 
                        "qiskit_ibm_provider", 
                        "quafu", 
                        "pandas", 
                        "qpandalite_cpp",
                        "qiskit-aer", 
                        "qutip",
                        "qutip_qip",
                        "matplotlib",
                        "matplotlib.pyplot",
                        "pyqpanda3"]

os.environ['SPHINX_DOC_GEN'] = '1'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh-CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'source/qpandalite.test.rst']
autodoc_typehints = "description"
autodoc_default_options = {
    'no-index': True,
}
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}

# -- Options for HTML output -------------------------------------------------

html_theme = "pydata_sphinx_theme"

import pydata_sphinx_theme, os
_html_theme_path = os.path.dirname(pydata_sphinx_theme.__file__)
html_theme_path = [_html_theme_path]

html_theme_options = {
    "show_nav_level": 2,
    "navigation_with_keys": True,
    "show_toc_level": 2,
    "header_links_before_dropdown": 6,

}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_js_files = ['hide_myst_anchors.js']

# pydata-sphinx-theme uses breadcrumbs by default; keep it enabled
breadcrumbs = True
