name: Pytest Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install package
      run: pip install .

    - name: Install test dependencies
      run: pip install pytest pytest-cov

    - name: Run tests with coverage
      run: pytest qpandalite/test/ --cov=qpandalite --cov-report=term-missing --cov-report=xml -v --deselect qpandalite/test/test_random_QASM.py::test_random_qasm_compare_density_operator --deselect qpandalite/test/test_random_QASM_measure.py::test_random_qasm_compare_shots_impl

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
